In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
# Load the dataset
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Drop unnecessary columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Encode categorical variable for gender
label_encode_gender = LabelEncoder()
data['Gender'] = label_encode_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# Encode categorical variables for geography using one-hot encoding
from sklearn.preprocessing import OneHotEncoder
one_hot_encode = OneHotEncoder()
geo_encoded = one_hot_encode.fit_transform(data[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
geo_encoded.toarray()
one_hot_encode.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=one_hot_encode.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
# Add the one-hot encoded columns back to the original dataframe and drop the original 'Geography' column
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [9]:
# save the encoder
with open('label_encode_gender.pkl', 'wb') as file:
    pickle.dump(label_encode_gender, file)

with open('one_hot_encode.pkl', 'wb') as file:
    pickle.dump(one_hot_encode, file)

In [10]:
# Separate features and target variable
X = data.drop('Exited', axis=1)
y = data['Exited']

#Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
#save the scaler
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Implementation

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
X_train.shape[1]

12

In [14]:
#Building the ANN model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #Hidden Layer 1 connected to input layer
    Dense(32, activation='relu'), #Hidden Layer 2 connected to Hidden Layer 1
    Dense(1, activation='sigmoid') #Output Layer connected to Hidden Layer 2

])

c:\Users\Anshuman Pandey\OneDrive\Desktop\ANN Classification\venv\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
opt = Adam(learning_rate=0.001)
loss = BinaryCrossentropy()

In [17]:
# Compile the model
model.compile(optimizer=opt, loss=loss, metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [18]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [19]:
# Define the log directory for TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [20]:
# Early stopping callback to prevent overfitting
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [21]:
# Train the model
history = model.fit(X_train, y_train, validation_data=(X_train, y_train), epochs=100, callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.8062 - loss: 0.4482 - val_accuracy: 0.8380 - val_loss: 0.3904
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8495 - loss: 0.3733 - val_accuracy: 0.8566 - val_loss: 0.3541
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8533 - loss: 0.3529 - val_accuracy: 0.8591 - val_loss: 0.3435
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8553 - loss: 0.3466 - val_accuracy: 0.8614 - val_loss: 0.3372
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8579 - loss: 0.3415 - val_accuracy: 0.8611 - val_loss: 0.3337
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8590 - loss: 0.3381 - val_accuracy: 0.8660 - val_loss: 0.3322
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8611 - loss: 0.3348 - val_accuracy: 0.8648 - val_loss: 0.3287
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8629 - loss: 0.3326 - val_accuracy: 0.8665 - val_loss: 0.3245
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8648 - loss: 0.3315 - val_accuracy: 0.8665 - val_loss: 0.3235
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8641 - loss: 0.3286 - val_accuracy: 0.8673 - val_loss: 0.3203
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8654 - loss: 0.3280 - val_accuracy: 0.8685 - val_loss: 0.3188
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8644 - loss: 0.3258 - val_accuracy: 0.8655 - val_loss: 0.3186
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8664 - loss: 0.3228 - val_accuracy: 0.8691 - val_loss: 0.3149
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8670 - loss: 0.3207 - val_accuracy: 0.8671 - val_loss: 0.3178
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8686 - loss: 0.3198 - val_accuracy: 0.8716 - val_loss: 0.3134
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8684 - loss: 0.3169 - val_accuracy: 0.8717 - val_loss: 0.3109
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8684 - loss: 0.3167 - val_accuracy: 0.8719 - val_loss: 0.3088
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8699 - loss: 0.3133 - val_accuracy: 0.8711 - val_loss: 0.3124
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8694 - loss: 0.3129 - val_accuracy: 0.8734 - val_loss: 0.3055
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8704 - loss: 0.3119 - val_accuracy: 0.8741 - val_loss: 0.3049
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8679 - loss: 0.3096 - val_accuracy: 0.8694 - val_loss: 0.3064
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8716 - loss: 0.3094 - val_accuracy: 0.8742 - val_loss: 0.3020
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8712 - loss: 0.3073 - val_accuracy: 0.8745 - val_loss: 0.2988
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8726 - loss: 0.3056 - val_accuracy: 0.8741 - val_loss: 0.3004
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8723 - loss: 0.3043 - val_accuracy: 0.8758 - val_loss: 0.2998
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8736 - loss: 0.3039 - val_accuracy: 0.8771 - val_loss: 0.2943
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8714 - loss: 0.3016 - val_accuracy: 0.8770 - val_loss: 0.2925
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8741 - loss: 0.3012 - val_accuracy: 0.8771 - val_loss: 0.2930
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8748 - loss: 0.2987 - val_accuracy: 0.8784 - val_loss: 0.2929
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8773 - loss: 0.2971 - val_accuracy: 0.8766 - val_loss: 0.2904
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8739 - loss: 0.2959 - val_accuracy: 0.8819 - val_loss: 0.2896
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8767 - loss: 0.2958 - val_accuracy: 0.8798 - val_loss: 0.2852
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8748 - loss: 0.2953 - val_accuracy: 0.8792 - val_loss: 0.2866
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8763 - loss: 0.2926 - val_accuracy: 0.8730 - val_loss: 0.2976
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8792 - loss: 0.2924 - val_accuracy: 0.8798 - val_loss: 0.2842
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8785 - loss: 0.2906 - val_accuracy: 0.8798 - val_loss: 0.2836
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8795 - loss: 0.2884 - val_accuracy: 0.8829 - val_loss: 0.2813
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8781 - loss: 0.2891 - val_accuracy: 0.8838 - val_loss: 0.2765
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8804 - loss: 0.2867 - val_accuracy: 0.8819 - val_loss: 0.2801
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8790 - loss: 0.2865 - val_accuracy: 0.8851 - val_loss: 0.2768
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8790 - loss: 0.2854 - val_accuracy: 0.8846 - val_loss: 0.2770
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8813 - loss: 0.2834 - val_accuracy: 0.8859 - val_loss: 0.2754
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8805 - loss: 0.2824 - val_accuracy: 0.8848 - val_loss: 0.2739
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8834 - loss: 0.2808 - val_accuracy: 0.8867 - val_loss: 0.2712
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8819 - loss: 0.2796 - val_accuracy: 0.8829 - val_loss: 0.2802
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8824 - loss: 0.2815 - val_accuracy: 0.8855 - val_loss: 0.2704
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8796 - loss: 0.2797 - val_accuracy: 0.8827 - val_loss: 0.2742
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8850 - loss: 0.2779 - val_accuracy: 0.8866 - val_loss: 0.2674
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8830 - loss: 0.2774 - val_accuracy: 0.8865 - val_loss: 0.2688
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8817 - loss: 0.2777 - val_accuracy: 0.8873 - val_loss: 0.2674
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8809 - loss: 0.2745 - val_accuracy: 0.8859 - val_loss: 0.2683
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8841 - loss: 0.2748 - val_accuracy: 0.8884 - val_loss: 0.2623
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8848 - loss: 0.2739 - val_accuracy: 0.8891 - val_loss: 0.2598
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8844 - loss: 0.2723 - val_accuracy: 0.8890 - val_loss: 0.2635
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8842 - loss: 0.2720 - val_accuracy: 0.8896 - val_loss: 0.2623
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8860 - loss: 0.2705 - val_accuracy: 0.8907 - val_loss: 0.2629
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8844 - loss: 0.2699 - val_accuracy: 0.8910 - val_loss: 0.2594
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8866 - loss: 0.2687 - val_accuracy: 0.8914 - val_loss: 0.2592
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8851 - loss: 0.2653 - val_accuracy: 0.8906 - val_loss: 0.2591
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8878 - loss: 0.2667 - val_accuracy: 0.8900 - val_loss: 0.2562
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8896 - loss: 0.2636 - val_accuracy: 0.8920 - val_loss: 0.2564
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8891 - loss: 0.2634 - val_accuracy: 0.8903 - val_loss: 0.2595
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8876 - loss: 0.2650 - val_accuracy: 0.8942 - val_loss: 0.2527
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8891 - loss: 0.2642 - val_accuracy: 0.8917 - val_loss: 0.2529
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8884 - loss: 0.2627 - val_accuracy: 0.8949 - val_loss: 0.2488
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8891 - loss: 0.2630 - val_accuracy: 0.8941 - val_loss: 0.2507
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8896 - loss: 0.2617 - val_accuracy: 0.8945 - val_loss: 0.2488
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8867 - loss: 0.2605 - val_accuracy: 0.8935 - val_loss: 0.2532
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8913 - loss: 0.2593 - val_accuracy: 0.8956 - val_loss: 0.2533
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8909 - loss: 0.2587 - val_accuracy: 0.8972 - val_loss: 0.2468
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8913 - loss: 0.2584 - val_accuracy: 0.8938 - val_loss: 0.2499
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8916 - loss: 0.2563 - val_accuracy: 0.8964 - val_loss: 0.2461
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8895 - loss: 0.2558 - val_accuracy: 0.8917 - val_loss: 0.2502
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8932 - loss: 0.2557 - val_accuracy: 0.8992 - val_loss: 0.2413
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8939 - loss: 0.2544 - val_accuracy: 0.8955 - val_loss: 0.2439
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8903 - loss: 0.2548 - val_accuracy: 0.8981 - val_loss: 0.2429
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8919 - loss: 0.2529 - val_accuracy: 0.8966 - val_loss: 0.2472
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8930 - loss: 0.2521 - val_accuracy: 0.8972 - val_loss: 0.2422
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8928 - loss: 0.2528 - val_accuracy: 0.8984 - val_loss: 0.2393
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8961 - loss: 0.2508 - val_accuracy: 0.8982 - val_loss: 0.2400
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8949 - loss: 0.2487 - val_accuracy: 0.9004 - val_loss: 0.2391
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8947 - loss: 0.2506 - val_accuracy: 0.8938 - val_loss: 0.2434
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8932 - loss: 0.2498 - val_accuracy: 0.8997 - val_loss: 0.2385
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8938 - loss: 0.2492 - val_accuracy: 0.9015 - val_loss: 0.2362
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8964 - loss: 0.2476 - val_accuracy: 0.8989 - val_loss: 0.2361
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8949 - loss: 0.2487 - val_accuracy: 0.9011 - val_loss: 0.2342
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8965 - loss: 0.2465 - val_accuracy: 0.8981 - val_loss: 0.2445
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8959 - loss: 0.2460 - val_accuracy: 0.8999 - val_loss: 0.2371
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8960 - loss: 0.2436 - val_accuracy: 0.9021 - val_loss: 0.2377
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8970 - loss: 0.2451 - val_accuracy: 0.9014 - val_loss: 0.2350
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8969 - loss: 0.2439 - val_accuracy: 0.9030 - val_loss: 0.2325
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8939 - loss: 0.2431 - val_accuracy: 0.9011 - val_loss: 0.2325
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8986 - loss: 0.2426 - val_accuracy: 0.9032 - val_loss: 0.2308
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8955 - loss: 0.2422 - val_accuracy: 0.9055 - val_loss: 0.2302
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8984 - loss: 0.2412 - val_accuracy: 0.9041 - val_loss: 0.2295
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8954 - loss: 0.2423 - val_accuracy: 0.9055 - val_loss: 0.2277
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8976 - loss: 0.2404 - val_accuracy: 0.9050 - val_loss: 0.2244
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8988 - loss: 0.2391 - val_accuracy: 0.9010 - val_loss: 0.2306
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8969 - loss: 0.2399 - val_accuracy: 0.9066 - val_loss: 0.2237
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8974 - loss: 0.2388 - val_accuracy: 0.9078 - val_loss: 0.2212

In [22]:
# Save the trained model
model.save('churn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [23]:
# Load the TensorBoard Extension
%load_ext tensorboard

In [25]:
%tensorboard --logdir logs/fit/20260327-155137/

Reusing TensorBoard on port 6006 (pid 24148), started 0:11:09 ago. (Use '!kill 24148' to kill it.)

In [27]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle   
import numpy as np
import pandas as pd

In [28]:
# Load the trained model
model = load_model('churn_model.h5')

# Load the scaler and encoders
with open('label_encode_gender.pkl', 'rb') as file:
    label_encode_gender = pickle.load(file)

with open('one_hot_encode.pkl', 'rb') as file:
    one_hot_encode = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [29]:
#Example input data for prediction
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender' : 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [ ]:
#One-hot encode the 'Geography' feature
geo_encoded = one_hot_encode.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encode.get_feature_names_out(['Geography']))

c:\Users\Anshuman Pandey\OneDrive\Desktop\ANN Classification\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [31]:
# Key-Value pairs to DataFrame
input_data_df = pd.DataFrame([input_data])

In [ ]:
# Label encode the 'Gender' feature
input_data_df['Gender'] = label_encode_gender.transform([input_data['Gender']])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [ ]:
# Add the one-hot encoded columns back to the original dataframe and drop the original 'Geography' column
input_data_df = pd.concat([input_data_df.drop('Geography', axis=1), geo_encoded_df], axis=1)
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [35]:
# Scale the input data
input_data_scaled = scaler.transform(input_data_df)

# Make a prediction
prediction = model.predict(input_data_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 571ms/step

array([[0.01325657]], dtype=float32)

In [36]:
prediction_probability = prediction[0][0]
prediction_probability
if prediction_probability > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.